/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import static Form.SuaThiSinh.arrTS;
import static Form.SuaThiSinh.executeStatement;
import QLTS.ExecuteStatement;
import QLTS.User;
import java.util.ArrayList;

/**
 *
 * @author buida
 */
public class DangNhap extends java.awt.Frame {
    
    ArrayList<User> arrUser = new ArrayList<>();
    static ExecuteStatement executeStatement;
    
    

    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
         arrUser = executeStatement.selectUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        txt_taikhoan = new java.awt.TextField();
        txt_matkhau = new java.awt.TextField();
        button_dangnhap = new java.awt.Button();

        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(390, 250));
        setSize(new java.awt.Dimension(390, 250));
        setTitle("Đăng nhập");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setText("Đăng nhập");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 29, -1, -1));

        label2.setText("Tài khoản");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 95, -1, -1));

        label3.setText("Mật khẩu");
        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));
        add(txt_taikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 95, 130, -1));
        add(txt_matkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 154, 130, -1));

        button_dangnhap.setLabel("Đăng nhập");
        button_dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_dangnhapActionPerformed(evt);
            }
        });
        add(button_dangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button_dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_dangnhapActionPerformed
        
        String tk = txt_taikhoan.getText().trim();
        String mk = txt_matkhau.getText().trim();
        
        System.out.println("tk: " + tk);
        System.out.println("mk: " + mk);
        boolean check = false;
        for (int i = 0; i < arrUser.size(); i++) {
            System.out.println(arrUser.get(i).getUserName() + " " + arrUser.get(i).getPassWord());
            if(arrUser.get(i).getUserName().toString().equals(tk) && arrUser.get(i).getPassWord().toString().equals(mk)){
                check = true;
                break;
            }
        }
        
        if(check == true){
            System.out.println("Đăng nhập thành công");
            //chuyen sang chuc nang
            
            
        }else{
            System.out.println("Tài khoản hoặc mật khẩu không đúng");
            //thong bao dang nhap khong thanh cong
        }
    }//GEN-LAST:event_button_dangnhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button_dangnhap;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextField txt_matkhau;
    private java.awt.TextField txt_taikhoan;
    // End of variables declaration//GEN-END:variables
}
