/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import QLTS.ConnectionDataBase;
import QLTS.DiaChi;
import QLTS.ExecuteStatement;
import QLTS.Khoi;
import QLTS.ThiSinh;
import QLTS.UpdatePrepareStatement;
import java.awt.Button;
import java.awt.Dialog;
import java.awt.FlowLayout;
import java.awt.Label;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class SuaThiSinh extends java.awt.Frame {

    static int index = 0;
    static ArrayList<ThiSinh> arrTS = new ArrayList<>();
    static UpdatePrepareStatement prepareStatement;
    static ExecuteStatement executeStatement;
    public Dialog d;
    private String data;
    int ck;

    /**
     * Creates new form SuaThiSinh
     */
    public SuaThiSinh(String data) {
        initComponents();
        choice1.addItem("Khối A");
        choice1.addItem("Khối B");
        choice1.addItem("Khối C");

        choice_ut.addItem("Nhóm 1");
        choice_ut.addItem("Nhóm 2");
        choice_ut.addItem("Nhóm 3");
//        
        this.add(popupMenu_ChucNamg);

        arrTS = executeStatement.selectThiSinh();

        this.data = data;
        if (this.data.equals("user")) {
            this.menuChucNang.setEnabled(false);
        }

        hienThiThongTin();
        if (index == 0) {
            btn_back.setEnabled(false);
        }
        if (index == arrTS.size() - 1) {
            btn_next.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private SuaThiSinh() {
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu_ChucNamg = new java.awt.PopupMenu();
        menuItem_pu_TTTS = new java.awt.MenuItem();
        menuItem_pu_Them = new java.awt.MenuItem();
        menuItem_pu_Xoa = new java.awt.MenuItem();
        menuItem_pu_DangXuat = new java.awt.MenuItem();
        menuItem_pu_Thoat = new java.awt.MenuItem();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        txt_timkiem = new java.awt.TextField();
        txt_hoten = new java.awt.TextField();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        btn_timkiem = new java.awt.Button();
        label5 = new java.awt.Label();
        txt_sbd = new java.awt.TextField();
        btn_sua = new java.awt.Button();
        tar_ttthisinh = new java.awt.TextArea();
        btn_next = new java.awt.Button();
        btn_back = new java.awt.Button();
        choice1 = new java.awt.Choice();
        choice_ut = new java.awt.Choice();
        panel2 = new java.awt.Panel();
        txt_sonha = new java.awt.TextField();
        txt_thanhpho = new java.awt.TextField();
        txt_duong = new java.awt.TextField();
        txt_quan = new java.awt.TextField();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        menuBar1 = new java.awt.MenuBar();
        menuTrangChu = new java.awt.Menu();
        menuItemThongTinTS = new java.awt.MenuItem();
        menuItemDangXuat = new java.awt.MenuItem();
        menuItemThoat = new java.awt.MenuItem();
        menuChucNang = new java.awt.Menu();
        menuItemThem = new java.awt.MenuItem();
        menuItemSua = new java.awt.MenuItem();
        menuItemXoa = new java.awt.MenuItem();

        popupMenu_ChucNamg.setLabel("Chức năng");
        popupMenu_ChucNamg.setName("");

        menuItem_pu_TTTS.setLabel("Trang chủ");
        menuItem_pu_TTTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_pu_TTTSActionPerformed(evt);
            }
        });
        popupMenu_ChucNamg.add(menuItem_pu_TTTS);
        menuItem_pu_TTTS.getAccessibleContext().setAccessibleParent(popupMenu_ChucNamg);

        menuItem_pu_Them.setLabel("Thêm thí sinh");
        menuItem_pu_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_pu_ThemActionPerformed(evt);
            }
        });
        popupMenu_ChucNamg.add(menuItem_pu_Them);
        menuItem_pu_Them.getAccessibleContext().setAccessibleParent(popupMenu_ChucNamg);

        menuItem_pu_Xoa.setLabel("Xóa thí sinh");
        menuItem_pu_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_pu_XoaActionPerformed(evt);
            }
        });
        popupMenu_ChucNamg.add(menuItem_pu_Xoa);
        menuItem_pu_Xoa.getAccessibleContext().setAccessibleParent(popupMenu_ChucNamg);

        menuItem_pu_DangXuat.setLabel("Đăng xuất");
        menuItem_pu_DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_pu_DangXuatActionPerformed(evt);
            }
        });
        popupMenu_ChucNamg.add(menuItem_pu_DangXuat);

        menuItem_pu_Thoat.setLabel("Thoát");
        menuItem_pu_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_pu_ThoatActionPerformed(evt);
            }
        });
        popupMenu_ChucNamg.add(menuItem_pu_Thoat);
        menuItem_pu_Thoat.getAccessibleContext().setAccessibleParent(popupMenu_ChucNamg);

        popupMenu_ChucNamg.getAccessibleContext().setAccessibleDescription("");
        popupMenu_ChucNamg.getAccessibleContext().setAccessibleParent(this);

        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(980, 500));
        setPreferredSize(new java.awt.Dimension(980, 540));
        setTitle("Sửa thông tin thí sinh");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setText("SỬA THÍ SINH");
        add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 50, 240, 50));

        label2.setText("Thông tin thí sinh: ");
        add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 172, -1, -1));

        txt_timkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_timkiemKeyTyped(evt);
            }
        });
        add(txt_timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 120, 20));
        add(txt_hoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 168, 170, -1));

        label3.setText("Ưu tiên:");
        add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 396, 50, -1));

        label4.setText("Họ tên:");
        add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 168, 50, -1));
        label4.getAccessibleContext().setAccessibleName("Họ tên");

        label10.setText("Địa chỉ:");
        add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 216, 50, -1));

        label11.setText("Khối:");
        add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 356, 40, -1));

        btn_timkiem.setLabel("Tìm kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });
        add(btn_timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, -1, -1));

        label5.setText("SBD:");
        add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 138, 40, -1));
        label5.getAccessibleContext().setAccessibleName("SBD");

        txt_sbd.setEditable(false);
        add(txt_sbd, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 138, 90, -1));

        btn_sua.setLabel("Sửa");
        btn_sua.setName(""); // NOI18N
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 472, 124, 33));

        tar_ttthisinh.setColumns(5);
        tar_ttthisinh.setEditable(false);
        tar_ttthisinh.setRows(89);
        add(tar_ttthisinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(532, 202, 420, 203));

        btn_next.setLabel("Next");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });
        add(btn_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(834, 438, -1, -1));

        btn_back.setLabel("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 438, -1, -1));

        choice1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                choice1PropertyChange(evt);
            }
        });
        add(choice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 396, 120, -1));
        add(choice_ut, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 356, 120, -1));

        panel2.setBackground(new java.awt.Color(153, 153, 153));

        txt_sonha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sonhaActionPerformed(evt);
            }
        });
        txt_sonha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_sonhaKeyTyped(evt);
            }
        });

        label13.setText("Số nhà");

        label14.setText("Thành phố");

        label15.setText("Quận");

        label16.setText("Đường");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_thanhpho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_sonha, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_quan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 118, Short.MAX_VALUE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(txt_duong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_sonha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_quan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_thanhpho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_duong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 206, -1, -1));

        menuTrangChu.setLabel("Trang chủ");

        menuItemThongTinTS.setLabel("Thông tin các thí sinh");
        menuItemThongTinTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemThongTinTSActionPerformed(evt);
            }
        });
        menuTrangChu.add(menuItemThongTinTS);

        menuItemDangXuat.setLabel("Đăng xuất");
        menuItemDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDangXuatActionPerformed(evt);
            }
        });
        menuTrangChu.add(menuItemDangXuat);

        menuItemThoat.setLabel("Thoát chương trình");
        menuItemThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemThoatActionPerformed(evt);
            }
        });
        menuTrangChu.add(menuItemThoat);

        menuBar1.add(menuTrangChu);

        menuChucNang.setLabel("Chức năng");
        menuChucNang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChucNangActionPerformed(evt);
            }
        });

        menuItemThem.setLabel("Thêm thí sinh");
        menuItemThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemThemActionPerformed(evt);
            }
        });
        menuChucNang.add(menuItemThem);

        menuItemSua.setLabel("Sửa thí sinh");
        menuItemSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSuaActionPerformed(evt);
            }
        });
        menuChucNang.add(menuItemSua);

        menuItemXoa.setLabel("Xóa thí sinh");
        menuItemXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemXoaActionPerformed(evt);
            }
        });
        menuChucNang.add(menuItemXoa);

        menuBar1.add(menuChucNang);

        setMenuBar(menuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        try {
            int idKhoi = 0;
            int sbd = Integer.valueOf(txt_sbd.getText().trim());

            int kt = checkDk();

            int check = -1;
            if (kt == 1) {
                String hoTen = txt_hoten.getText();
                int soNha = Integer.valueOf(txt_sonha.getText().trim());
                String duong = txt_duong.getText().trim();
                String quan = txt_quan.getText().trim();
                String thanhPho = txt_thanhpho.getText().trim();
                String khoi = choice1.getSelectedItem().toString();
                String uuTien = choice_ut.getSelectedItem().toString();

                DiaChi dc = new DiaChi(soNha, duong, quan, thanhPho);
                Khoi k = new Khoi(khoi);
                ThiSinh TS = new ThiSinh(sbd, hoTen, k, dc, uuTien);
//        check = UpdatePrepareStatement.updateTS(TS);
                d = new Dialog(this, "Thông báo", true);
                d.setLayout(new FlowLayout());
                Button b = new Button("OK");
                Button b1 = new Button("NO");
                b.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        ck = -1000;
                        d.setVisible(false);
                    }
                });

                b1.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        ck = 1;
                        d.setVisible(false);
                    }
                });

                d.add(new Label("Bạn có chắc muốn sửa thông tin thí sinh này!                  "));
                d.add(b);
                d.add(b1);
                System.out.println("check sx " + check);
                d.setSize(300, 150);
                d.setLocationRelativeTo(this);
                d.setVisible(true);
                if (ck != 1) {
                    check = UpdatePrepareStatement.updateTS(TS);
//                        xoaTS(ts);
                    showDialog("Sửa thông tin thí sinh thành công!                              ");
                    btn_sua.setEnabled(true);
                    hienThiThongTin();
                }

            }

//        if (check != -1) {
//            System.out.println("sua thanh cong");
//            arrTS = executeStatement.selectThiSinh();
//            showDialog("Sửa thông tin thí sinh thành công!           ");
//        btn_sua.setEnabled(true);
//            hienThiThongTin();
//
//        } else {
//            System.out.println("sua that bai");
//            showDialog("Sửa thông tin thất bại!                      ");
//        btn_sua.setEnabled(true);
//        }
        } catch (Exception e) {
            showDialog("Nhập các thông tin cần sửa của thí sinh!                  ");
        }

    }//GEN-LAST:event_btn_suaActionPerformed

    private void choice1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_choice1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_choice1PropertyChange

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        int vtri = 0;

        if (txt_timkiem.getText().length() <= 0) {
            showDialog("Hãy nhập số báo danh vào ô tìm kiếm!            ");
            btn_sua.setEnabled(true);
            return;
        }

        int sbd = Integer.valueOf(txt_timkiem.getText());
        boolean tk = false;
        for (int i = 0; i < arrTS.size(); i++) {
            if (Integer.valueOf(arrTS.get(i).getSbd()) == sbd) {
                tk = true;
                vtri = i;
                index = i;
                break;
            }
        }
        if (tk == true) {
            hienThiThongTin();

        } else {
            showDialog("Số báo danh không tồn tại!                          ");
            btn_sua.setEnabled(true);

            tar_ttthisinh.setText("Số báo danh không hợp lệ");
            txt_sbd.setText("");
            txt_hoten.setText("");
            txt_sonha.setText("");
            txt_duong.setText("");
            txt_quan.setText("");
            txt_thanhpho.setText("");
            choice1.select(0);
            choice_ut.select(0);

        }
        btn_back.setEnabled(true);
        btn_next.setEnabled(true);
        if (index == 0) {
            btn_back.setEnabled(false);
        }
        if (index == arrTS.size() - 1) {
            btn_next.setEnabled(false);
        }

    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:

        System.out.println(index);
        btn_next.setEnabled(true);
        if (index >= 1) {
            btn_back.setEnabled(true);
            index -= 1;
            if (index == 0) {
                btn_back.setEnabled(false);
            }
            hienThiThongTin();
//            
        } else {
            btn_back.setEnabled(false);
        }
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:

        System.out.println(index);

        btn_back.setEnabled(true);

        if (index < arrTS.size() - 1) {
            btn_next.setEnabled(true);
            index += 1;
            if (index == arrTS.size() - 1) {
                btn_next.setEnabled(false);
            }

            hienThiThongTin();
//          
        } else {
            btn_next.setEnabled(false);
        }

    }//GEN-LAST:event_btn_nextActionPerformed

    private void txt_timkiemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_timkiemKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_timkiemKeyTyped

    private void txt_sonhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sonhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sonhaActionPerformed

    private void txt_sonhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sonhaKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_sonhaKeyTyped

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

        // TODO add your handling code here:
        popupMenu_ChucNamg.show(this, evt.getX(), evt.getY());

    }//GEN-LAST:event_formMouseClicked

    private void menuItem_pu_TTTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_pu_TTTSActionPerformed
        // TODO add your handling code here:
        ThongTinThiSinh ttts = new ThongTinThiSinh(this.data);
        ttts.show();
        dispose();
    }//GEN-LAST:event_menuItem_pu_TTTSActionPerformed

    private void menuItem_pu_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_pu_ThemActionPerformed
        // TODO add your handling code here:
        ThemThiSinh them = new ThemThiSinh(this.data);
        them.show();
        dispose();
    }//GEN-LAST:event_menuItem_pu_ThemActionPerformed

    private void menuItem_pu_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_pu_XoaActionPerformed
        // TODO add your handling code here:
        XoaThiSinh xoa = new XoaThiSinh(this.data);
        xoa.show();
        dispose();
    }//GEN-LAST:event_menuItem_pu_XoaActionPerformed

    private void menuItem_pu_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_pu_ThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_menuItem_pu_ThoatActionPerformed

    private void menuItemThongTinTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemThongTinTSActionPerformed
        ThongTinThiSinh ttts = new ThongTinThiSinh(this.data);
        ttts.show();
        dispose();
    }//GEN-LAST:event_menuItemThongTinTSActionPerformed

    private void menuItemDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDangXuatActionPerformed
        // TODO add your handling code here:
        DangNhap dn = new DangNhap();
        dn.show();
        dispose();
    }//GEN-LAST:event_menuItemDangXuatActionPerformed

    private void menuItemThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_menuItemThoatActionPerformed

    private void menuItemThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemThemActionPerformed
        new ThemThiSinh(this.data).setVisible(true);
        dispose();
    }//GEN-LAST:event_menuItemThemActionPerformed

    private void menuItemSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSuaActionPerformed

        //        try {
        //            new SuaThiSinh().setVisible(true);
        //        } catch (SQLException ex) {
        //            Logger.getLogger(XoaThiSinh.class.getName()).log(Level.SEVERE, null, ex);
        //        } catch (ClassNotFoundException ex) {
        //            Logger.getLogger(XoaThiSinh.class.getName()).log(Level.SEVERE, null, ex);
        //        }
        new SuaThiSinh(this.data).setVisible(true);

        dispose();
    }//GEN-LAST:event_menuItemSuaActionPerformed

    private void menuItemXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemXoaActionPerformed
        new XoaThiSinh(this.data).setVisible(true);
        dispose();
    }//GEN-LAST:event_menuItemXoaActionPerformed

    private void menuChucNangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChucNangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuChucNangActionPerformed

    private void menuItem_pu_DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_pu_DangXuatActionPerformed
        // TODO add your handling code here:
        DangNhap dn = new DangNhap();
        dn.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuItem_pu_DangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaThiSinh().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_back;
    private java.awt.Button btn_next;
    private java.awt.Button btn_sua;
    private java.awt.Button btn_timkiem;
    private java.awt.Choice choice1;
    private java.awt.Choice choice_ut;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.MenuBar menuBar1;
    private java.awt.Menu menuChucNang;
    private java.awt.MenuItem menuItemDangXuat;
    private java.awt.MenuItem menuItemSua;
    private java.awt.MenuItem menuItemThem;
    private java.awt.MenuItem menuItemThoat;
    private java.awt.MenuItem menuItemThongTinTS;
    private java.awt.MenuItem menuItemXoa;
    private java.awt.MenuItem menuItem_pu_DangXuat;
    private java.awt.MenuItem menuItem_pu_TTTS;
    private java.awt.MenuItem menuItem_pu_Them;
    private java.awt.MenuItem menuItem_pu_Thoat;
    private java.awt.MenuItem menuItem_pu_Xoa;
    private java.awt.Menu menuTrangChu;
    private java.awt.Panel panel2;
    private java.awt.PopupMenu popupMenu_ChucNamg;
    private java.awt.TextArea tar_ttthisinh;
    private java.awt.TextField txt_duong;
    private java.awt.TextField txt_hoten;
    private java.awt.TextField txt_quan;
    private java.awt.TextField txt_sbd;
    private java.awt.TextField txt_sonha;
    private java.awt.TextField txt_thanhpho;
    private java.awt.TextField txt_timkiem;
    // End of variables declaration//GEN-END:variables

    public void hienThiThongTin() {
        String ss = "";
        String schoice = "", uchoice = "";
        ss += arrTS.get(index).getSbd() + "\n\n";
        ss += arrTS.get(index).getHoTen() + "\n\n";
        ss += arrTS.get(index).getDiaChi().getSoNha() + ", ";
        ss += arrTS.get(index).getDiaChi().getDuong() + ", ";
        ss += arrTS.get(index).getDiaChi().getQuan() + ", ";
        ss += arrTS.get(index).getDiaChi().getThanhPho() + "\n\n";
        ss += arrTS.get(index).getKhoi().getTenKhoi() + ": \t";
        ss += arrTS.get(index).getKhoi().getMon1() + ", ";
        ss += arrTS.get(index).getKhoi().getMon2() + ", ";
        ss += arrTS.get(index).getKhoi().getMon3() + "\n\n";
        ss += arrTS.get(index).getUuTien() + "\n\n";

        tar_ttthisinh.setText(ss);
        txt_sbd.setText(arrTS.get(index).getSbd() + "");
        txt_hoten.setText(arrTS.get(index).getHoTen() + "");
        txt_sonha.setText(String.valueOf(arrTS.get(index).getDiaChi().getSoNha()));
        txt_duong.setText(arrTS.get(index).getDiaChi().getDuong());
        txt_quan.setText(arrTS.get(index).getDiaChi().getQuan());
        txt_thanhpho.setText(arrTS.get(index).getDiaChi().getThanhPho());
        schoice = arrTS.get(index).getKhoi().getTenKhoi().toString().trim();
        uchoice = arrTS.get(index).getUuTien().toString().trim();

        //set index choice
        if (schoice.equals("Khối A")) {
            choice1.select("Khối A");
        } else if (schoice.equals("Khối B")) {
            choice1.select("Khối B");
        } else {
            choice1.select("Khối C");
        }
        //set index choice uu tien
        if (uchoice.equals("Nhóm 1")) {
            choice_ut.select("Nhóm 1");
        } else if (uchoice.equals("Nhóm 2")) {
            choice_ut.select("Nhóm 2");
        } else {
            choice_ut.select("Nhóm 3");
        }
    }

    public void showDialog(String s) {
        d = new Dialog(this, "Thông báo", true);
        d.setLayout(new FlowLayout());
        Button b = new Button("OK");
        b.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                d.setVisible(false);
                d.dispose();
//                    setVisible(true);
//                    SuaThiSinh sts = new SuaThiSinh("user");
//                    sts.show();
            }
        });
        d.add(new Label(s));
        d.add(b);
        d.setSize(300, 150);
        d.setLocationRelativeTo(this);
        d.setVisible(true);
    }

    public int checkDk() {
        if (txt_hoten.getText().length() <= 0) {
            showDialog("Bạn chưa nhập họ tên thí sinh!");
            return 0;
        }
        if (txt_sonha.getText().length() <= 0) {
            showDialog("Bạn chưa nhập số nhà!");
            return 0;
        }
        if (txt_sonha.getText().length() >= 10) {
            showDialog("Số nhà không được lớn hơn 10 ký tự!");
            return 0;
        }
        if (txt_duong.getText().length() <= 0) {
            showDialog("Bạn chưa nhập tên đường!");
            return 0;
        }
        if (txt_quan.getText().length() <= 0) {
            showDialog("Bạn chưa nhập tên quận!");
            return 0;
        }
        if (txt_thanhpho.getText().length() <= 0) {
            showDialog("Bạn chưa nhập tên thành phố!");
            return 0;
        }
        return 1;
    }
}
