/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import QLTS.ConnectionDataBase;
import QLTS.DiaChi;
import QLTS.ExecuteStatement;
import QLTS.Khoi;
import QLTS.ThiSinh;
import QLTS.UpdatePrepareStatement;
import java.awt.Dialog;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class SuaThiSinh extends java.awt.Frame {

    
    static int index = 0;
    static ArrayList<ThiSinh> arrTS = new ArrayList<>();
    static UpdatePrepareStatement prepareStatement;
    static ExecuteStatement executeStatement;

    /**
     * Creates new form SuaThiSinh
     */
    public SuaThiSinh() throws SQLException, ClassNotFoundException {
        initComponents();
        choice1.addItem("Khối A");
        choice1.addItem("Khối B");
        choice1.addItem("Khối C");

        choice_ut.addItem("Nhóm 1");
        choice_ut.addItem("Nhóm 2");
        choice_ut.addItem("Nhóm 3");

        arrTS = executeStatement.selectThiSinh();
//        Connection conn = (Connection) connect.getConnectDB();
//        Statement stm = null;
//        ResultSet rs = null;
//        String s = "select SBD,HoTen,SoNha,Duong,Quan,ThanhPho,TenKhoi,Mon1,Mon2, Mon3, UuTien \n"
//                + "	from ThiSinh inner join DiaChi on ThiSinh.IdDiaChi = DiaChi.IdDiaChi\n"
//                + "	inner join Khoi on ThiSinh.IdKhoi = Khoi.IdKhoi";
//        stm = conn.createStatement();
//        rs = stm.executeQuery(s);

//        ResultSet rs = executeStatement.selectThiSinh();
//        while (rs.next()) {
//            DiaChi dc = new DiaChi(Integer.valueOf(rs.getString(3)), rs.getString(4), rs.getString(5), rs.getString(6));
//            Khoi k = new Khoi(rs.getString(7), rs.getString(8), rs.getString(9), rs.getString(10));
//            ThiSinh ts = new ThiSinh(Integer.valueOf(rs.getString(1)), rs.getString(2), k, dc, rs.getString(11));//5- 11
//            arrTS.add(ts);
//        }
//        conn.close();
        String ss = "";
//                textField1.setText("");
        //hien thi danh sach thi sinh
//        for (int j = 0; j < 20; j++) {
//            for (int i = 0; i < arrTS.size(); i++) {
            int i = 0;
                int sbd = arrTS.get(i).getSbd();
                String hoTen = arrTS.get(i).getHoTen().trim();
                int soNha = Integer.valueOf(arrTS.get(i).getDiaChi().getSoNha());
                String duong = arrTS.get(i).getDiaChi().getDuong().trim();
                String quan = arrTS.get(i).getDiaChi().getQuan().trim();
                String thanhPho = arrTS.get(i).getDiaChi().getThanhPho().trim();
                String khoi = arrTS.get(i).getKhoi().getTenKhoi().trim();
                String uuTien = arrTS.get(i).getUuTien().trim();
                tar_ttthisinh.setText( sbd + "\n" + hoTen + "\n" +khoi + "\n" +thanhPho + "\n" +uuTien + "\n");
//            }
//        }
int vtri = i;String schoice = "", uchoice = "";
            txt_sbd.setText(arrTS.get(vtri).getSbd() + "");
            txt_hoten.setText(arrTS.get(vtri).getHoTen() + "");
            txt_sonha.setText(String.valueOf(arrTS.get(vtri).getDiaChi().getSoNha()));
            txt_duong.setText(arrTS.get(vtri).getDiaChi().getDuong());
            txt_quan.setText(arrTS.get(vtri).getDiaChi().getQuan());
            txt_thanhpho.setText(arrTS.get(vtri).getDiaChi().getThanhPho());
            schoice += arrTS.get(vtri).getKhoi().getTenKhoi().toString().trim();
            uchoice += arrTS.get(vtri).getUuTien().toString().trim();
            
            
            //set index choice
            if (schoice.equals("Khối A")) {
                choice1.select("Khối A");
            } else if (schoice.equals("Khối B")) {
                choice1.select("Khối B");
            } else {
                choice1.select("Khối C");
            }
            //set index choice uu tien
            if (uchoice.equals("Nhóm 1")) {

                choice_ut.select("Nhóm 1");
            } else if (uchoice.equals("Nhóm 2")) {
                choice_ut.select("Nhóm 2");
            } else {
                choice_ut.select("Nhóm 3");
            }
            

        if (index == 0) {
            btn_back.setEnabled(false);
        }
        if (index == arrTS.size() - 1) {
            btn_next.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        txt_timkiem = new java.awt.TextField();
        txt_hoten = new java.awt.TextField();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        btn_timkiem = new java.awt.Button();
        label5 = new java.awt.Label();
        txt_sbd = new java.awt.TextField();
        btn_sua = new java.awt.Button();
        tar_ttthisinh = new java.awt.TextArea();
        btn_next = new java.awt.Button();
        btn_back = new java.awt.Button();
        choice1 = new java.awt.Choice();
        choice_ut = new java.awt.Choice();
        panel2 = new java.awt.Panel();
        txt_sonha = new java.awt.TextField();
        txt_thanhpho = new java.awt.TextField();
        txt_duong = new java.awt.TextField();
        txt_quan = new java.awt.TextField();
        label13 = new java.awt.Label();
        label14 = new java.awt.Label();
        label15 = new java.awt.Label();
        label16 = new java.awt.Label();
        menuBar1 = new java.awt.MenuBar();
        m_ttts = new java.awt.Menu();
        m_themts = new java.awt.Menu();
        nav_themts = new java.awt.MenuItem();
        m_suats = new java.awt.Menu();
        m_xoats = new java.awt.Menu();
        nav_xoats = new java.awt.MenuItem();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(1000, 650));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setText("SỬA THÍ SINH");

        label2.setText("Thông tin thí sinh: ");

        txt_timkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_timkiemKeyTyped(evt);
            }
        });

        label3.setText("Ưu tiên:");

        label4.setText("Họ tên:");

        label10.setText("Địa chỉ:");

        label11.setText("Khối:");

        btn_timkiem.setLabel("Tìm kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        label5.setText("SBD:");

        txt_sbd.setEditable(false);

        btn_sua.setLabel("Sửa");
        btn_sua.setName(""); // NOI18N
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        tar_ttthisinh.setColumns(5);
        tar_ttthisinh.setEditable(false);
        tar_ttthisinh.setRows(89);

        btn_next.setLabel("Next");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        btn_back.setLabel("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        choice1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                choice1PropertyChange(evt);
            }
        });

        panel2.setBackground(new java.awt.Color(204, 204, 204));

        txt_sonha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sonhaActionPerformed(evt);
            }
        });
        txt_sonha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_sonhaKeyTyped(evt);
            }
        });

        label13.setText("Số nhà");

        label14.setText("Thành phố");

        label15.setText("Quận");

        label16.setText("Đường");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_thanhpho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_sonha, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_quan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 118, Short.MAX_VALUE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(txt_duong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_sonha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_quan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_thanhpho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_duong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        m_ttts.setLabel("Thông tin thí sinh");
        menuBar1.add(m_ttts);

        m_themts.setLabel("Thêm thí sinh");

        nav_themts.setLabel("menuItem1");
        nav_themts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nav_themtsActionPerformed(evt);
            }
        });
        m_themts.add(nav_themts);

        menuBar1.add(m_themts);

        m_suats.setLabel("Sửa thí sinh");
        menuBar1.add(m_suats);

        m_xoats.setLabel("Xóa thí sinh");
        m_xoats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_xoatsActionPerformed(evt);
            }
        });

        nav_xoats.setLabel("menuItem1");
        nav_xoats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nav_xoatsActionPerformed(evt);
            }
        });
        m_xoats.add(nav_xoats);

        menuBar1.add(m_xoats);

        setMenuBar(menuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(txt_sbd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(choice_ut, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tar_ttthisinh, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(69, 69, 69)
                                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(190, 190, 190)
                                    .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(78, 78, 78)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(415, 415, 415)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(357, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sbd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choice_ut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tar_ttthisinh, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        label4.getAccessibleContext().setAccessibleName("Họ tên");
        label5.getAccessibleContext().setAccessibleName("SBD");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed

//        String sbdc = txt_sbd.getText().trim();
//        if(sbdc == null|| sbdc == ""){
//         
//            JOptionPane.showMessageDialog(this,
//            "bạn chưa chọn thi sinh cần sửa",
//             "Inane warning",
//                JOptionPane.WARNING_MESSAGE);
//            
//        }
        
        int idKhoi = 0;
        int sbd = Integer.valueOf(txt_sbd.getText().trim());
        String hoTen = txt_hoten.getText();
        int soNha = Integer.valueOf(txt_sonha.getText().trim());
        String duong = txt_duong.getText().trim();
        String quan = txt_quan.getText().trim();
        String thanhPho = txt_thanhpho.getText().trim();
        String khoi = choice1.getSelectedItem().toString();
        String uuTien = choice_ut.getSelectedItem().toString();
//        String mon1,mon2,mon3;
        // sua trong sql
//        if(khoi == "Khối A"){
//            idKhoi = 1;
//            mon1 = "Toán";
//            mon2 = "Lý";
//            mon3 = "Hóa";
//        }else if(khoi == "Khối B"){
//            idKhoi = 2;
//            mon1 = "Toán";
//            mon2 = "Hóa";
//            mon3 = "Sinh";
//        }else {
//            idKhoi = 3;
//            mon1 = "Văn";
//            mon2 = "Sử";
//            mon3 = "Địa";
//        }
        DiaChi dc = new DiaChi(soNha, duong, quan, thanhPho);
        Khoi k = new Khoi(khoi);
        ThiSinh TS = new ThiSinh(sbd, hoTen, k, dc, uuTien);
        int check = UpdatePrepareStatement.updateTS(TS);
        if (check != -1) {
            System.out.println("sua thanh cong");
            arrTS = executeStatement.selectThiSinh();

            String ss = "";
            String schoice = "", uchoice = "";
            ss += arrTS.get(index).getSbd() + "\n";
            ss += arrTS.get(index).getHoTen() + "\n";
            ss += arrTS.get(index).getKhoi().getTenKhoi() + "\n";
            ss += arrTS.get(index).getDiaChi().getThanhPho() + "\n";
            ss += arrTS.get(index).getUuTien() + "\n";

            tar_ttthisinh.setText(ss);
            txt_sbd.setText(arrTS.get(index).getSbd() + "");
            txt_hoten.setText(arrTS.get(index).getHoTen() + "");
            txt_sonha.setText(String.valueOf(arrTS.get(index).getDiaChi().getSoNha()));
            txt_duong.setText(arrTS.get(index).getDiaChi().getDuong());
            txt_quan.setText(arrTS.get(index).getDiaChi().getQuan());
            txt_thanhpho.setText(arrTS.get(index).getDiaChi().getThanhPho());
            schoice = arrTS.get(index).getKhoi().getTenKhoi().toString().trim();
            uchoice = arrTS.get(index).getUuTien().toString().trim();

            //set index choice
            if (schoice.equals("Khối A")) {
                choice1.select("Khối A");
            } else if (schoice.equals("Khối B")) {
                choice1.select("Khối B");
            } else {
                choice1.select("Khối C");
            }
            //set index choice uu tien
            if (uchoice.equals("Nhóm 1")) {
                choice_ut.select("Nhóm 1");
            } else if (uchoice.equals("Nhóm 2")) {
                choice_ut.select("Nhóm 2");
            } else {
                choice_ut.select("Nhóm 3");
            }

        } else {
            System.out.println("sua that bai");
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void choice1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_choice1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_choice1PropertyChange

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
         btn_sua.setEnabled(true);
        int vtri = 0;
        int sbd = Integer.valueOf(txt_timkiem.getText());
        boolean tk = false;
        for (int i = 0; i < arrTS.size(); i++) {
            if (Integer.valueOf(arrTS.get(i).getSbd()) == sbd) {
                tk = true;
                vtri = i;
                index = i;
                break;
            }
        }
        if (tk == true) {
            String ss = "";
            String schoice = "", uchoice = "";
            ss += arrTS.get(vtri).getSbd() + "\n";
            ss += arrTS.get(vtri).getHoTen() + "\n";
            ss += arrTS.get(vtri).getKhoi().getTenKhoi() + "\n";
            ss += arrTS.get(vtri).getDiaChi().getThanhPho() + "\n";
            ss += arrTS.get(vtri).getUuTien() + "\n";

            tar_ttthisinh.setText(ss);
            txt_sbd.setText(arrTS.get(vtri).getSbd() + "");
            txt_hoten.setText(arrTS.get(vtri).getHoTen() + "");
            txt_sonha.setText(String.valueOf(arrTS.get(vtri).getDiaChi().getSoNha()));
            txt_duong.setText(arrTS.get(vtri).getDiaChi().getDuong());
            txt_quan.setText(arrTS.get(vtri).getDiaChi().getQuan());
            txt_thanhpho.setText(arrTS.get(vtri).getDiaChi().getThanhPho());
            schoice += arrTS.get(vtri).getKhoi().getTenKhoi().toString().trim();
            uchoice += arrTS.get(vtri).getUuTien().toString().trim();

            //set index choice
            if (schoice.equals("Khối A")) {
                choice1.select("Khối A");
            } else if (schoice.equals("Khối B")) {
                choice1.select("Khối B");
            } else {
                choice1.select("Khối C");
            }
            //set index choice uu tien
            if (uchoice.equals("Nhóm 1")) {

                choice_ut.select("Nhóm 1");
            } else if (uchoice.equals("Nhóm 2")) {
                choice_ut.select("Nhóm 2");
            } else {
                choice_ut.select("Nhóm 3");
            }

        } else {
            tar_ttthisinh.setText("Số báo danh không hợp lệ");
            txt_sbd.setText("");
            txt_hoten.setText("");
            txt_sonha.setText("");
            txt_duong.setText("");
            txt_quan.setText("");
            txt_thanhpho.setText("");
            choice1.select(0);
            choice_ut.select(0);
            btn_sua.setEnabled(false);

        }
        btn_back.setEnabled(true);
        btn_next.setEnabled(true);
        if (index == 0) {
            btn_back.setEnabled(false);
        }
        if (index == arrTS.size() - 1) {
            btn_next.setEnabled(false);
        }

    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:

        System.out.println(index);
        btn_next.setEnabled(true);
        if (index >= 1) {
            btn_back.setEnabled(true);
            index -= 1;
            if (index == 0) {
                btn_back.setEnabled(false);
            }
            String ss = "";
            String schoice = "", uchoice = "";
            ss += arrTS.get(index).getSbd() + "\n";
            ss += arrTS.get(index).getHoTen() + "\n";
            ss += arrTS.get(index).getKhoi().getTenKhoi() + "\n";
            ss += arrTS.get(index).getDiaChi().getThanhPho() + "\n";
            ss += arrTS.get(index).getUuTien() + "\n";

            tar_ttthisinh.setText(ss);
            txt_sbd.setText(arrTS.get(index).getSbd() + "");
            txt_hoten.setText(arrTS.get(index).getHoTen() + "");
            txt_sonha.setText(String.valueOf(arrTS.get(index).getDiaChi().getSoNha()));
            txt_duong.setText(arrTS.get(index).getDiaChi().getDuong());
            txt_quan.setText(arrTS.get(index).getDiaChi().getQuan());
            txt_thanhpho.setText(arrTS.get(index).getDiaChi().getThanhPho());
            schoice += arrTS.get(index).getKhoi().getTenKhoi().toString().trim();
            uchoice += arrTS.get(index).getUuTien().toString().trim();

            //set index choice
            if (schoice.equals("Khối A")) {
                choice1.select("Khối A");
            } else if (schoice.equals("KhốiB")) {
                choice1.select("Khối B");
            } else {
                choice1.select("Khối C");
            }
            //set index choice uu tien
            if (uchoice.equals("Nhóm 1")) {

                choice_ut.select("Nhóm 1");
            } else if (uchoice.equals("Nhóm 2")) {
                choice_ut.select("Nhóm 2");
            } else {
                choice_ut.select("Nhóm 3");
            }
        } else {
            btn_back.setEnabled(false);
        }
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:

        System.out.println(index);

        btn_back.setEnabled(true);

        if (index < arrTS.size() - 1) {
            btn_next.setEnabled(true);
            index += 1;
            if (index == arrTS.size() - 1) {
                btn_next.setEnabled(false);
            }

            String ss = "";
            String schoice = "", uchoice = "";
            ss += arrTS.get(index).getSbd() + "\n";
            ss += arrTS.get(index).getHoTen() + "\n";
            ss += arrTS.get(index).getKhoi().getTenKhoi() + "\n";
            ss += arrTS.get(index).getDiaChi().getThanhPho() + "\n";
            ss += arrTS.get(index).getUuTien() + "\n";

            tar_ttthisinh.setText(ss);
            txt_sbd.setText(arrTS.get(index).getSbd() + "");
            txt_hoten.setText(arrTS.get(index).getHoTen() + "");
            txt_sonha.setText(String.valueOf(arrTS.get(index).getDiaChi().getSoNha()));
            txt_duong.setText(arrTS.get(index).getDiaChi().getDuong());
            txt_quan.setText(arrTS.get(index).getDiaChi().getQuan());
            txt_thanhpho.setText(arrTS.get(index).getDiaChi().getThanhPho());
            schoice += arrTS.get(index).getKhoi().getTenKhoi().toString().trim();
            uchoice += arrTS.get(index).getUuTien().toString().trim();

            //set index choice
            if (schoice.equals("Khối A")) {
                choice1.select("Khối A");
            } else if (schoice.equals("Khối B")) {
                choice1.select("Khối B");
            } else {
                choice1.select("Khối C");
            }
            //set index choice uu tien
            if (uchoice.equals("Nhóm 1")) {

                choice_ut.select("Nhóm 1");
            } else if (uchoice.equals("Nhóm 2")) {
                choice_ut.select("Nhóm 2");
            } else {
                choice_ut.select("Nhóm 3");
            }
        } else {
            btn_next.setEnabled(false);
        }

    }//GEN-LAST:event_btn_nextActionPerformed

    private void txt_timkiemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_timkiemKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_timkiemKeyTyped

    private void m_xoatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_xoatsActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_m_xoatsActionPerformed

    private void nav_xoatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nav_xoatsActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_nav_xoatsActionPerformed

    private void nav_themtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nav_themtsActionPerformed
        // TODO add your handling code here:
        ThemThiSinh t = new ThemThiSinh();
        t.show();
        dispose();
    }//GEN-LAST:event_nav_themtsActionPerformed

    private void txt_sonhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sonhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sonhaActionPerformed

    private void txt_sonhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sonhaKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_sonhaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SuaThiSinh().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(SuaThiSinh.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(SuaThiSinh.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_back;
    private java.awt.Button btn_next;
    private java.awt.Button btn_sua;
    private java.awt.Button btn_timkiem;
    private java.awt.Choice choice1;
    private java.awt.Choice choice_ut;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Menu m_suats;
    private java.awt.Menu m_themts;
    private java.awt.Menu m_ttts;
    private java.awt.Menu m_xoats;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuItem nav_themts;
    private java.awt.MenuItem nav_xoats;
    private java.awt.Panel panel2;
    private java.awt.TextArea tar_ttthisinh;
    private java.awt.TextField txt_duong;
    private java.awt.TextField txt_hoten;
    private java.awt.TextField txt_quan;
    private java.awt.TextField txt_sbd;
    private java.awt.TextField txt_sonha;
    private java.awt.TextField txt_thanhpho;
    private java.awt.TextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
