/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import static Form.SuaThiSinh.arrTS;
import static Form.SuaThiSinh.executeStatement;
import static Form.SuaThiSinh.index;
import QLTS.ConnectionDataBase;
import QLTS.DiaChi;
import QLTS.Khoi;
import QLTS.ThiSinh;
import QLTS.ExecuteStatement;
import QLTS.UpdatePrepareStatement;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class ThemThiSinh extends java.awt.Frame {

    static int index = 1;
    static ArrayList<QLTS.ThiSinh> arrTS = new ArrayList<>();
    static UpdatePrepareStatement prepareStatement;
    static ExecuteStatement executeStatement;

    /**
     * Creates new form ThemThiSinh
     */
    public ThemThiSinh() {
        initComponents();
         choice1.addItem("Khối A");
        choice1.addItem("Khối B");
        choice1.addItem("Khối C");

        choice_ut.addItem("Nhóm 1");
        choice_ut.addItem("Nhóm 2");
        choice_ut.addItem("Nhóm 3");

        arrTS = executeStatement.selectThiSinh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        label1 = new java.awt.Label();
        txt_timkiem = new java.awt.TextField();
        label3 = new java.awt.Label();
        panel1 = new java.awt.Panel();
        txt_sonha = new java.awt.TextField();
        txt_thanhpho = new java.awt.TextField();
        txt_duong = new java.awt.TextField();
        txt_quan = new java.awt.TextField();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        choice1 = new java.awt.Choice();
        choice_ut = new java.awt.Choice();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        btn_timkiem = new java.awt.Button();
        tar_ttthisinh = new java.awt.TextArea();
        btn_them = new java.awt.Button();
        btn_next = new java.awt.Button();
        btn_back = new java.awt.Button();
        txt_hoten = new java.awt.TextField();
        label10 = new java.awt.Label();
        menuBar2 = new java.awt.MenuBar();
        menuTrangChu = new java.awt.Menu();
        menuItemThongTinTS = new java.awt.MenuItem();
        menuItemThoat = new java.awt.MenuItem();
        menuChucNang = new java.awt.Menu();
        menuItemSua = new java.awt.MenuItem();
        menuItemXoa = new java.awt.MenuItem();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        label1.setName(""); // NOI18N
        label1.setText("THÊM THÍ SINH");

        txt_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timkiemActionPerformed(evt);
            }
        });

        label3.setText("Họ và Tên");

        panel1.setBackground(new java.awt.Color(204, 204, 204));

        txt_sonha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sonhaActionPerformed(evt);
            }
        });

        label4.setText("Số nhà");

        label5.setText("Thành phố");

        label6.setText("Quận");

        label7.setText("Đường");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_thanhpho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_sonha, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_quan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 118, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(txt_duong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_sonha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_quan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_thanhpho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_duong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label6.getAccessibleContext().setAccessibleName("");

        label8.setText("Khối");

        label9.setText("KV Ưu Tiên");

        btn_timkiem.setLabel("Tìm Kiếm");
        btn_timkiem.setName("Tìm Kiếm"); // NOI18N
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        btn_them.setLabel("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_next.setLabel("Next");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        btn_back.setLabel("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        label10.setText("Địa Chỉ");

        menuTrangChu.setLabel("Trang chủ");

        menuItemThongTinTS.setLabel("Thông tin các thí sinh");
        menuTrangChu.add(menuItemThongTinTS);

        menuItemThoat.setLabel("Thoát chương trình");
        menuItemThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemThoatActionPerformed(evt);
            }
        });
        menuTrangChu.add(menuItemThoat);

        menuBar2.add(menuTrangChu);

        menuChucNang.setLabel("Chức năng");

        menuItemSua.setLabel("Sửa thí sinh");
        menuItemSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSuaActionPerformed(evt);
            }
        });
        menuChucNang.add(menuItemSua);

        menuItemXoa.setLabel("Xóa thí sinh");
        menuItemXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemXoaActionPerformed(evt);
            }
        });
        menuChucNang.add(menuItemXoa);

        menuBar2.add(menuChucNang);

        setMenuBar(menuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(645, 645, 645)
                        .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choice_ut, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(tar_ttthisinh, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(327, 327, 327)
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tar_ttthisinh, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(140, 140, 140)
                                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(choice_ut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void txt_sonhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sonhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sonhaActionPerformed

    private void txt_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timkiemActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        int vtri = 0;
        int sbd = Integer.valueOf(txt_timkiem.getText());
        boolean tk = false;
        for (int i = 0; i < arrTS.size(); i++) {
            if (arrTS.get(i).getSbd() == sbd) {
                tk = true;
                vtri = i;
                index = i;
                break;
            }
        }
        if (tk == true) {
            String ss = "";
            String schoice = "", uchoice = "";
            ss += arrTS.get(vtri).getSbd() + "\t";
            ss += arrTS.get(vtri).getHoTen() + "\t";
            ss += "Khối " + arrTS.get(vtri).getKhoi().getTenKhoi() + "\t";
            ss += arrTS.get(vtri).getDiaChi().getThanhPho() + "\t";
            ss += arrTS.get(vtri).getUuTien() + "\t";

            tar_ttthisinh.setText(ss);
//            txt_sbd.setText(arrTS.get(vtri).getSbd() + "");
            txt_hoten.setText(arrTS.get(vtri).getHoTen() + "");
            txt_sonha.setText(String.valueOf(arrTS.get(vtri).getDiaChi().getSoNha()));
            txt_duong.setText(arrTS.get(vtri).getDiaChi().getDuong());
            txt_quan.setText(arrTS.get(vtri).getDiaChi().getQuan());
            txt_thanhpho.setText(arrTS.get(vtri).getDiaChi().getThanhPho());
            schoice += arrTS.get(vtri).getKhoi().getTenKhoi().toString().trim();
            uchoice += arrTS.get(vtri).getUuTien().toString().trim();

            //set index choice
            if (schoice.equals("A")) {
                choice1.select("Khối A");
            } else if (schoice.equals("B")) {
                choice1.select("Khối B");
            } else {
                choice1.select("Khối C");
            }
            //set index choice uu tien
            if (uchoice.equals("Nhóm 1")) {

                choice_ut.select("Nhóm 1");
            } else if (uchoice.equals("Nhóm 2")) {
                choice_ut.select("Nhóm 2");
            } else {
                choice_ut.select("Nhóm 3");
            }

        } else {
            tar_ttthisinh.setText("Số báo danh không hợp lệ");
//            txt_sbd.setText("");
            txt_hoten.setText("");
            txt_sonha.setText("");
            txt_duong.setText("");
            txt_quan.setText("");
            txt_thanhpho.setText("");
            choice1.select(0);
            choice_ut.select(0);

        }
        if (index == 0) {
            btn_back.setEnabled(false);
        }
        if (index == arrTS.size() - 1) {
            btn_next.setEnabled(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
//        System.out.println(index);
//
//        btn_back.setEnabled(true);
//
//        if (index < arrTS.size() - 1) {
//            btn_next.setEnabled(true);
//            index += 1;
//            if (index == arrTS.size() - 1) {
//                btn_next.setEnabled(false);
//            }
//
//            String ss = "";
//            String schoice = "", uchoice = "";
//            ss += arrTS.get(index).getSbd() + "\t";
//            ss += arrTS.get(index).getHoTen() + "\t";
//            ss += "Khối " + arrTS.get(index).getKhoi().getTenKhoi() + "\t";
//            ss += arrTS.get(index).getDiaChi().getThanhPho() + "\t";
//            ss += arrTS.get(index).getUuTien() + "\t";
//
//            tar_ttthisinh.setText(ss);
//            txt_sbd.setText(arrTS.get(index).getSbd() + "");
//            txt_hoten.setText(arrTS.get(index).getHoTen() + "");
//            txt_sonha.setText(String.valueOf(arrTS.get(index).getDiaChi().getSoNha()));
//            txt_duong.setText(arrTS.get(index).getDiaChi().getDuong());
//            txt_quan.setText(arrTS.get(index).getDiaChi().getQuan());
//            txt_thanhpho.setText(arrTS.get(index).getDiaChi().getThanhPho());
//            schoice += arrTS.get(index).getKhoi().getTenKhoi().trim();
//            uchoice += arrTS.get(index).getUuTien().trim();
//
//            //set index choice
//            if (schoice.equals("A")) {
//                choice1.select("Khối A");
//            } else if (schoice.equals("B")) {
//                choice1.select("Khối B");
//            } else {
//                choice1.select("Khối C");
//            }
//            //set index choice uu tien
//            if (uchoice.equals("Nhóm 1")) {
//
//                choice_ut.select("Nhóm 1");
//            } else if (uchoice.equals("Nhóm 2")) {
//                choice_ut.select("Nhóm 2");
//            } else {
//                choice_ut.select("Nhóm 3");
//            }
//        } else {
//            btn_next.setEnabled(false);
//        }

        System.out.println(index);

        btn_back.setEnabled(true);

        if (index < arrTS.size() - 1) {
            btn_next.setEnabled(true);
            index += 1;
            if (index == arrTS.size() - 1) {
                btn_next.setEnabled(false);
            }

            String ss = "";
            String schoice = "", uchoice = "";
            ss += arrTS.get(index).getSbd() + "\n";
            ss += arrTS.get(index).getHoTen() + "\n";
            ss += arrTS.get(index).getKhoi().getTenKhoi() + "\n";
            ss += arrTS.get(index).getDiaChi().getThanhPho() + "\n";
            ss += arrTS.get(index).getUuTien() + "\n";

            tar_ttthisinh.setText(ss);
//            txt_sbd.setText(arrTS.get(index).getSbd() + "");
            txt_hoten.setText(arrTS.get(index).getHoTen() + "");
            txt_sonha.setText(String.valueOf(arrTS.get(index).getDiaChi().getSoNha()));
            txt_duong.setText(arrTS.get(index).getDiaChi().getDuong());
            txt_quan.setText(arrTS.get(index).getDiaChi().getQuan());
            txt_thanhpho.setText(arrTS.get(index).getDiaChi().getThanhPho());
            schoice += arrTS.get(index).getKhoi().getTenKhoi().toString().trim();
            uchoice += arrTS.get(index).getUuTien().toString().trim();

            //set index choice
            if (schoice.equals("Khối A")) {
                choice1.select("Khối A");
            } else if (schoice.equals("Khối B")) {
                choice1.select("Khối B");
            } else {
                choice1.select("Khối C");
            }
            //set index choice uu tien
            if (uchoice.equals("Nhóm 1")) {

                choice_ut.select("Nhóm 1");
            } else if (uchoice.equals("Nhóm 2")) {
                choice_ut.select("Nhóm 2");
            } else {
                choice_ut.select("Nhóm 3");
            }
        } else {
            btn_next.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
//        System.out.println(index);
//        btn_next.setEnabled(true);
//        if (index >= 1) {
//            btn_back.setEnabled(true);
//            index -= 1;
//            if (index == 0) {
//                btn_back.setEnabled(false);
//            }
//            String ss = "";
//            String schoice = "", uchoice = "";
//            ss += arrTS.get(index).getSbd() + "\t";
//            ss += arrTS.get(index).getHoTen() + "\t";
//            ss += "Khối " + arrTS.get(index).getKhoi().getTenKhoi() + "\t";
//            ss += arrTS.get(index).getDiaChi().getThanhPho() + "\t";
//            ss += arrTS.get(index).getUuTien() + "\t";
//
//            tar_ttthisinh.setText(ss);
//            txt_sbd.setText(arrTS.get(index).getSbd() + "");
//            txt_hoten.setText(arrTS.get(index).getHoTen() + "");
//            txt_sonha.setText(String.valueOf(arrTS.get(index).getDiaChi().getSoNha()));
//            txt_duong.setText(arrTS.get(index).getDiaChi().getDuong());
//            txt_quan.setText(arrTS.get(index).getDiaChi().getQuan());
//            txt_thanhpho.setText(arrTS.get(index).getDiaChi().getThanhPho());
//            schoice += arrTS.get(index).getKhoi().getTenKhoi().trim();
//            uchoice += arrTS.get(index).getUuTien().trim();
//
//            //set index choice
//            if (schoice.equals("A")) {
//                choice1.select("Khối A");
//            } else if (schoice.equals("B")) {
//                choice1.select("Khối B");
//            } else {
//                choice1.select("Khối C");
//            }
//            //set index choice uu tien
//            if (uchoice.equals("Nhóm 1")) {
//
//                choice_ut.select("Nhóm 1");
//            } else if (uchoice.equals("Nhóm 2")) {
//                choice_ut.select("Nhóm 2");
//            } else {
//                choice_ut.select("Nhóm 3");
//            }
//        } else {
//            btn_back.setEnabled(false);
//        }        // TODO add your handling code here:
System.out.println(index);
        btn_next.setEnabled(true);
        if (index >= 1) {
            btn_back.setEnabled(true);
            index -= 1;
            if (index == 0) {
                btn_back.setEnabled(false);
            }
            String ss = "";
            String schoice = "", uchoice = "";
            ss += arrTS.get(index).getSbd() + "\n";
            ss += arrTS.get(index).getHoTen() + "\n";
            ss += arrTS.get(index).getKhoi().getTenKhoi() + "\n";
            ss += arrTS.get(index).getDiaChi().getThanhPho() + "\n";
            ss += arrTS.get(index).getUuTien() + "\n";

            tar_ttthisinh.setText(ss);
//            txt_sbd.setText(arrTS.get(index).getSbd() + "");
            txt_hoten.setText(arrTS.get(index).getHoTen() + "");
            txt_sonha.setText(String.valueOf(arrTS.get(index).getDiaChi().getSoNha()));
            txt_duong.setText(arrTS.get(index).getDiaChi().getDuong());
            txt_quan.setText(arrTS.get(index).getDiaChi().getQuan());
            txt_thanhpho.setText(arrTS.get(index).getDiaChi().getThanhPho());
            schoice += arrTS.get(index).getKhoi().getTenKhoi().toString().trim();
            uchoice += arrTS.get(index).getUuTien().toString().trim();

            //set index choice
            if (schoice.equals("Khối A")) {
                choice1.select("Khối A");
            } else if (schoice.equals("KhốiB")) {
                choice1.select("Khối B");
            } else {
                choice1.select("Khối C");
            }
            //set index choice uu tien
            if (uchoice.equals("Nhóm 1")) {

                choice_ut.select("Nhóm 1");
            } else if (uchoice.equals("Nhóm 2")) {
                choice_ut.select("Nhóm 2");
            } else {
                choice_ut.select("Nhóm 3");
            }
        } else {
            btn_back.setEnabled(false);
        }
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        
//        int sbd = Integer.valueOf(txt_sbd.getText().trim());
        String hoTen = txt_hoten.getText();
        int soNha = Integer.valueOf(txt_sonha.getText().trim());
        String duong = txt_duong.getText().trim();
        String quan = txt_quan.getText().trim();
        String thanhPho = txt_thanhpho.getText().trim();
        String khoi = choice1.getSelectedItem().toString();
        String uuTien = choice_ut.getSelectedItem().toString();

        QLTS.DiaChi dc = new QLTS.DiaChi(soNha, duong, quan, thanhPho);
        QLTS.Khoi k = new QLTS.Khoi(khoi);
        QLTS.ThiSinh TS = new QLTS.ThiSinh(hoTen, k, dc, uuTien);
        int check = UpdatePrepareStatement.insertTS(TS);
        if (check != -1) {
            
            System.out.println("Them thanh cong");
            arrTS = executeStatement.selectThiSinh();
            index = arrTS.size()-1;
            String ss = "";
            String schoice = "", uchoice = "";
            ss += arrTS.get(index).getSbd() + "\t";
            ss += arrTS.get(index).getHoTen() + "\t";
            ss += arrTS.get(index).getKhoi().getTenKhoi() + "\t";
            ss += arrTS.get(index).getDiaChi().getThanhPho() + "\t";
            ss += arrTS.get(index).getUuTien() + "\t";

            tar_ttthisinh.setText(ss);
//            txt_sbd.setText(arrTS.get(index).getSbd() + "");
            txt_hoten.setText(arrTS.get(index).getHoTen() + "");
            txt_sonha.setText(String.valueOf(arrTS.get(index).getDiaChi().getSoNha()));
            txt_duong.setText(arrTS.get(index).getDiaChi().getDuong());
            txt_quan.setText(arrTS.get(index).getDiaChi().getQuan());
            txt_thanhpho.setText(arrTS.get(index).getDiaChi().getThanhPho());
            schoice = arrTS.get(index).getKhoi().getTenKhoi().toString().trim();
            uchoice = arrTS.get(index).getUuTien().toString().trim();

            //set index choice
            if (schoice.equals("Khối A")) {
                choice1.select("Khối A");
            } else if (schoice.equals("Khối B")) {
                choice1.select("Khối B");
            } else {
                choice1.select("Khối C");
            }
            //set index choice uu tien
            if (uchoice.equals("Nhóm 1")) {
                choice_ut.select("Nhóm 1");
            } else if (uchoice.equals("Nhóm 2")) {
                choice_ut.select("Nhóm 2");
            } else {
                choice_ut.select("Nhóm 3");
            }

        } else {
            System.out.println("them that bai");
        }

    }//GEN-LAST:event_btn_themActionPerformed

    private void menuItemThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_menuItemThoatActionPerformed

    private void menuItemSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSuaActionPerformed
        try {
            // TODO add your handling code here:
            SuaThiSinh sua = new SuaThiSinh();
            sua.show();
            
        } catch (SQLException ex) {
            Logger.getLogger(ThemThiSinh.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ThemThiSinh.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_menuItemSuaActionPerformed

    private void menuItemXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemXoaActionPerformed
        // TODO add your handling code here:
        XoaThiSinh xoa = new XoaThiSinh();
        xoa.show();
        dispose();
    }//GEN-LAST:event_menuItemXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemThiSinh().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_back;
    private java.awt.Button btn_next;
    private java.awt.Button btn_them;
    private java.awt.Button btn_timkiem;
    private java.awt.Choice choice1;
    private java.awt.Choice choice_ut;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.MenuBar menuBar2;
    private java.awt.Menu menuChucNang;
    private java.awt.MenuItem menuItemSua;
    private java.awt.MenuItem menuItemThoat;
    private java.awt.MenuItem menuItemThongTinTS;
    private java.awt.MenuItem menuItemXoa;
    private java.awt.Menu menuTrangChu;
    private java.awt.Panel panel1;
    private java.awt.TextArea tar_ttthisinh;
    private java.awt.TextArea textArea1;
    private java.awt.TextField txt_duong;
    private java.awt.TextField txt_hoten;
    private java.awt.TextField txt_quan;
    private java.awt.TextField txt_sonha;
    private java.awt.TextField txt_thanhpho;
    private java.awt.TextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
